name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Preparation du projet
        run: |
          flutter create --project-name cardio_app --org com.cardio.app dossier_temp
          cp pubspec.yaml dossier_temp/pubspec.yaml
          cp -r lib/* dossier_temp/lib/

      - name: Compilation APK
        run: |
          cd dossier_temp
          flutter pub get
          flutter build apk --release

      - name: Telechargement APK
        uses: actions/upload-artifact@v4
        with:
          name: CardioApp-Android-APK
          path: dossier_temp/build/app/outputs/flutter-apk/app-release.apk
